"use client";

/**
 * The live trip panel: everything known about the trip, beside the conversation.
 *
 * **The problem this solves is scrolling, not styling.** A chat transcript is
 * chronological, so the map, the photographs and the hotel list scroll away
 * the moment the traveller replies. Asking "and the weather?" pushed the
 * weather off screen by the time it arrived. Anything that describes the
 * *current state of the trip* belongs somewhere that does not move, which is
 * here; the conversation keeps the things that are genuinely a sequence.
 *
 * **Every panel has three states and shows which one it is in.** Empty, with
 * a line saying what to ask for; loading, as a skeleton; or filled. A panel
 * that renders nothing when it has nothing is indistinguishable from a broken
 * one, and the commonest complaint about this app was people not knowing
 * whether a feature existed or had failed.
 *
 * **Provenance is on the panel, not in a footnote.** Flight and hotel prices
 * here are generated - Amadeus withdrew its free tier - and a made-up price
 * rendered in the same style as a real forecast is the most misleading thing
 * this interface could do. Simulated panels say so on their own header, in
 * their own colour, every time.
 */

import { useEffect, useState } from "react";

import {
  IconBed,
  IconCalendar,
  IconInfo,
  IconPin,
  IconPlane,
  IconSun,
  IconUsers,
  IconWallet,
} from "@/components/icons";
import {
  PlaceMap,
  dayColor,
  type BaseLayerName,
  type MappedItem,
} from "@/components/PlaceMap";
import { PlacePhoto } from "@/components/PlacePhoto";
import type { ChatResponse, TripFact, TripState } from "@/lib/api";

/** What a panel currently knows. */
type PanelState = "empty" | "loading" | "ready";

/**
 * A panel shell: title, provenance, and an honest empty state.
 *
 * The `hint` is deliberately phrased as something to say rather than a
 * description of the absence. "Ask about hotels" tells a traveller how to fill
 * it; "No hotel data" tells them nothing they cannot already see.
 */
function Panel({
  title,
  icon,
  state,
  hint,
  fact,
  action,
  ask,
  askLabel = "Ask now",
  onAsk,
  children,
}: {
  title: string;
  icon: React.ReactNode;
  state: PanelState;
  hint: string;
  fact?: TripFact;
  action?: React.ReactNode;
  /** The message the button sends. Omitted when there is nothing sensible
   *  to ask yet - offering "find me a hotel" before a destination is known
   *  just produces a clarifying question. */
  ask?: string;
  askLabel?: string;
  onAsk?: (message: string) => void;
  children?: React.ReactNode;
}) {
  return (
    <section className="overflow-hidden rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)]">
      <header className="flex items-center gap-2 px-3 py-2.5">
        <span className="text-[var(--color-brand)]">{icon}</span>
        <h3 className="flex-1 font-display text-xs font-semibold">{title}</h3>
        {action}
        {fact && <ProvenanceChip fact={fact} />}
      </header>

      <div className="px-3 pb-3">
        {state === "empty" && (
          <div className="rounded-xl bg-[var(--color-surface-2)] px-3 py-2.5">
            <p className="flex items-start gap-1.5 text-[11px] leading-relaxed text-[var(--color-ink-faint)]">
              <IconInfo size="0.9em" className="mt-0.5 shrink-0" />
              {hint}
            </p>
            {/* The button sends the same sentence the traveller would have
                typed, rather than calling a tool directly. Everything then
                flows through the one path that keeps the conversation, the
                memory and the trace consistent - and the transcript still
                reads as something a person said. */}
            {onAsk && ask && (
              <button
                type="button"
                onClick={() => onAsk(ask)}
                className="mt-2 inline-flex min-h-8 items-center gap-1 rounded-full border border-[var(--color-brand)]/40 bg-[var(--color-brand-soft)] px-2.5 text-[11px] font-medium text-[var(--color-brand-strong)] transition-colors duration-200 hover:border-[var(--color-brand)]"
              >
                {askLabel}
              </button>
            )}
          </div>
        )}
        {state === "loading" && <div className="skeleton h-20 w-full rounded-xl" />}
        {state === "ready" && children}
      </div>
    </section>
  );
}

/**
 * Where a panel's numbers came from.
 *
 * Two visually distinct states rather than one label with different text,
 * because the difference between a measured forecast and an invented price is
 * the single most important thing on the panel and must survive a glance.
 */
function ProvenanceChip({ fact }: { fact: TripFact }) {
  if (fact.simulated) {
    return (
      <span
        title={`Generated by the ${fact.source} provider. Not real availability or pricing.`}
        className="rounded-full bg-[var(--color-warn-soft)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-[var(--color-warn)]"
      >
        Simulated
      </span>
    );
  }
  return (
    <span
      title={`Live data from ${fact.source}.`}
      className="rounded-full bg-[var(--color-mint-soft)] px-2 py-0.5 text-[10px] font-medium text-[var(--color-mint)]"
    >
      {fact.source}
    </span>
  );
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-3 py-1 text-[11px]">
      <span className="text-[var(--color-ink-faint)]">{label}</span>
      <span className="min-w-0 truncate text-right font-medium">{value}</span>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Panels
// ---------------------------------------------------------------------------

function TripSummary({ trip }: { trip: TripState }) {
  const known = [
    trip.destination && { icon: <IconPin size="0.9em" />, label: "Where", value: trip.destination },
    trip.duration_days && {
      icon: <IconCalendar size="0.9em" />,
      label: "How long",
      value: `${trip.duration_days} days`,
    },
    (trip.start_date || trip.travel_window) && {
      icon: <IconCalendar size="0.9em" />,
      label: "When",
      value: trip.start_date ?? trip.travel_window,
    },
    trip.origin && { icon: <IconPlane size="0.9em" />, label: "From", value: trip.origin },
    trip.party && { icon: <IconUsers size="0.9em" />, label: "Who", value: trip.party },
    trip.budget_tier && {
      icon: <IconWallet size="0.9em" />,
      label: "Budget",
      value: trip.budget_tier,
    },
  ].filter(Boolean) as { icon: React.ReactNode; label: string; value: string }[];

  return (
    <Panel
      title="Your trip"
      icon={<IconCompassLite />}
      state={known.length > 0 ? "ready" : "empty"}
      hint="Tell me where you'd like to go and the details will collect here."
    >
      <div className="divide-y divide-[var(--color-line)]">
        {known.map((row) => (
          <Row key={row.label} label={row.label} value={row.value} />
        ))}
      </div>
      {Array.isArray(trip.priorities) && trip.priorities.length > 0 && (
        <div className="mt-2 flex flex-wrap gap-1">
          {(trip.priorities as string[]).map((priority) => (
            <span
              key={priority}
              className="rounded-full bg-[var(--color-brand-soft)] px-2 py-0.5 text-[10px] font-medium text-[var(--color-brand-strong)]"
            >
              {priority}
            </span>
          ))}
        </div>
      )}
    </Panel>
  );
}

function IconCompassLite() {
  return <IconPin size="1em" />;
}

function WeatherPanel({
  fact,
  busy,
  trip,
  onAsk,
}: {
  fact?: TripFact;
  busy: boolean;
  trip: TripState;
  onAsk?: (message: string) => void;
}) {
  const data = fact?.data as
    | {
        location?: string;
        days?: {
          date: string;
          temp_max_c?: number | null;
          temp_min_c?: number | null;
          conditions?: string | null;
          precipitation_chance_pct?: number | null;
        }[];
        typical_high_c?: number;
        typical_low_c?: number;
      }
    | undefined;

  const days = (data?.days ?? []).slice(0, 4);
  const state: PanelState = fact ? "ready" : busy ? "loading" : "empty";

  return (
    <Panel
      title="Weather"
      icon={<IconSun size="1em" />}
      state={state}
      hint={
        trip.destination
          ? "The forecast lands here once it has been looked up."
          : "Name a destination and its forecast lands here."
      }
      fact={fact}
      onAsk={onAsk}
      askLabel="Check the weather"
      // Only offered once there is somewhere to check. Without a date the
      // question includes that gap deliberately, so the agent asks for the
      // dates rather than silently assuming some.
      ask={
        trip.destination
          ? trip.start_date || trip.travel_window
            ? `What's the weather like in ${trip.destination} for those dates?`
            : `What's the weather like in ${trip.destination}?`
          : undefined
      }
    >
      {days.length > 0 ? (
        <div className="grid grid-cols-4 gap-1.5">
          {days.map((day) => (
            <div
              key={day.date}
              className="rounded-xl bg-[var(--color-surface-2)] px-1.5 py-2 text-center"
            >
              <p className="text-[9px] uppercase tracking-wide text-[var(--color-ink-faint)]">
                {new Date(day.date).toLocaleDateString(undefined, { weekday: "short" })}
              </p>
              <p className="mt-0.5 font-display text-sm font-semibold">
                {day.temp_max_c != null ? `${Math.round(day.temp_max_c)}°` : "—"}
              </p>
              <p className="text-[9px] text-[var(--color-ink-faint)]">
                {day.temp_min_c != null ? `${Math.round(day.temp_min_c)}°` : ""}
              </p>
              {day.precipitation_chance_pct != null && day.precipitation_chance_pct > 20 && (
                <p className="text-[9px] text-[var(--color-sky)]">
                  {Math.round(day.precipitation_chance_pct)}%
                </p>
              )}
            </div>
          ))}
        </div>
      ) : (
        <div className="text-[11px]">
          {data?.typical_high_c != null ? (
            <>
              <Row label="Typical high" value={`${data.typical_high_c}°C`} />
              <Row label="Typical low" value={`${data.typical_low_c}°C`} />
              <p className="mt-1 text-[10px] text-[var(--color-ink-faint)]">
                Seasonal averages — the dates are too far out for a forecast.
              </p>
            </>
          ) : (
            <p className="text-[var(--color-ink-faint)]">No forecast for these dates.</p>
          )}
        </div>
      )}
    </Panel>
  );
}

function StaysPanel({
  fact,
  busy,
  destination,
  onAsk,
}: {
  fact?: TripFact;
  busy: boolean;
  destination: string;
  onAsk?: (message: string) => void;
}) {
  const data = fact?.data as
    | {
        properties?: {
          name: string;
          category?: string;
          stars?: number;
          guest_rating?: number;
          price_per_night_usd?: number;
        }[];
        currency?: string;
      }
    | undefined;

  const stays = (data?.properties ?? []).slice(0, 3);
  const state: PanelState = fact ? "ready" : busy ? "loading" : "empty";

  return (
    <Panel
      title="Places to stay"
      icon={<IconBed size="1em" />}
      state={state}
      hint={
        destination
          ? "Places to stay appear here, with photographs."
          : "Name a destination and places to stay appear here."
      }
      fact={fact}
      onAsk={onAsk}
      askLabel="Find places to stay"
      ask={destination ? `Where should I stay in ${destination}?` : undefined}
    >
      {stays.length > 0 ? (
        <ul className="space-y-1.5">
          {stays.map((stay) => (
            <li key={stay.name} className="flex gap-2">
              <PlacePhoto
                name={stay.name}
                destination={destination}
                latitude={null}
                longitude={null}
                kind="stay"
                className="h-12 w-16 shrink-0"
              />
              <div className="min-w-0 flex-1">
                <p className="truncate text-[11px] font-medium">{stay.name}</p>
                <p className="text-[10px] text-[var(--color-ink-faint)]">
                  {stay.guest_rating != null && `${stay.guest_rating}/10`}
                  {stay.stars != null && ` · ${stay.stars}★`}
                </p>
              </div>
              {stay.price_per_night_usd != null && (
                <span className="shrink-0 self-center text-[11px] font-semibold tabular-nums">
                  ${Math.round(stay.price_per_night_usd)}
                  <span className="text-[9px] font-normal text-[var(--color-ink-faint)]">/night</span>
                </span>
              )}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-[11px] text-[var(--color-ink-faint)]">
          Nothing matched that budget.
        </p>
      )}
    </Panel>
  );
}

function FlightsPanel({
  fact,
  busy,
  trip,
  onAsk,
}: {
  fact?: TripFact;
  busy: boolean;
  trip: TripState;
  onAsk?: (message: string) => void;
}) {
  const data = fact?.data as
    | {
        route?: { from?: string; to?: string };
        offers?: {
          carrier: string;
          flight_number?: string;
          departure_at?: string;
          stop_label?: string;
          price_total_usd?: number;
        }[];
      }
    | undefined;

  const offers = (data?.offers ?? []).slice(0, 3);
  const state: PanelState = fact ? "ready" : busy ? "loading" : "empty";

  return (
    <Panel
      title="Flights"
      icon={<IconPlane size="1em" />}
      state={state}
      hint={
        trip.origin
          ? "Flight options appear here."
          : "Say where you're flying from and options appear here."
      }
      fact={fact}
      onAsk={onAsk}
      askLabel="Look up flights"
      ask={
        trip.destination
          ? trip.origin
            ? `Find flights from ${trip.origin} to ${trip.destination}.`
            : `Find me flights to ${trip.destination}.`
          : undefined
      }
    >
      {offers.length > 0 ? (
        <ul className="space-y-1">
          {offers.map((offer, index) => (
            <li
              key={`${offer.carrier}-${index}`}
              className="flex items-center gap-2 rounded-xl bg-[var(--color-surface-2)] px-2 py-1.5"
            >
              <div className="min-w-0 flex-1">
                <p className="truncate text-[11px] font-medium">{offer.carrier}</p>
                <p className="text-[10px] text-[var(--color-ink-faint)]">
                  {offer.departure_at?.slice(11)} · {offer.stop_label}
                </p>
              </div>
              {offer.price_total_usd != null && (
                <span className="shrink-0 text-[11px] font-semibold tabular-nums">
                  ${Math.round(offer.price_total_usd)}
                </span>
              )}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-[11px] text-[var(--color-ink-faint)]">No flights found for that route.</p>
      )}
    </Panel>
  );
}

function MapPanel({
  pins,
  busy,
  destination,
}: {
  pins: MappedItem[];
  busy: boolean;
  destination: string;
}) {
  const [expanded, setExpanded] = useState(false);
  const [active, setActive] = useState<number | null>(null);
  const state: PanelState = pins.length > 0 ? "ready" : busy ? "loading" : "empty";

  return (
    <>
      <Panel
        title={pins.length > 0 ? `Map · ${pins.length} stops` : "Map"}
        icon={<IconPin size="1em" />}
        state={state}
        hint="Places get pinned here as soon as the agent names some."
        action={
          pins.length > 0 ? (
            <button
              type="button"
              onClick={() => setExpanded(true)}
              className="rounded-full border border-[var(--color-line-strong)] px-2 py-0.5 text-[10px] font-medium transition-colors duration-200 hover:border-[var(--color-brand)] hover:text-[var(--color-brand-strong)]"
            >
              Expand
            </button>
          ) : undefined
        }
      >
        <PlaceMap
          items={pins}
          activeIndex={active}
          onHoverItem={setActive}
          className="h-52 rounded-xl"
        />
        <p className="mt-1.5 text-[10px] leading-relaxed text-[var(--color-ink-faint)]">
          Numbered in visiting order and joined by a dashed line. Only places
          that resolved confidently are pinned — a missing pin is deliberate,
          not a failure.
        </p>
      </Panel>

      {expanded && (
        <ExpandedMap pins={pins} destination={destination} onClose={() => setExpanded(false)} />
      )}
    </>
  );
}

/**
 * The whole map, full screen, with the stop list beside it.
 *
 * A 200px panel is enough to see that stops cluster; it is not enough to read
 * a route. Rather than making the panel taller and pushing the rest of the
 * trip off screen, the detail lives behind one control.
 */
function ExpandedMap({
  pins,
  destination,
  onClose,
}: {
  pins: MappedItem[];
  destination: string;
  onClose: () => void;
}) {
  const [active, setActive] = useState<number | null>(null);
  const [focus, setFocus] = useState<number | null>(null);
  const [layer, setLayer] = useState<BaseLayerName>("Map");

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey);
    const { overflow } = document.body.style;
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = overflow;
    };
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Trip map"
      className="fade-in fixed inset-0 z-50 flex flex-col bg-[var(--color-paper)] p-3 sm:p-5"
    >
      <header className="flex flex-wrap items-center gap-2 pb-3">
        <h2 className="flex-1 font-display text-base font-semibold">{pins.length} stops</h2>

        {/* Satellite is the one people want for a holiday: a street map says
            where the fort is, imagery says what it looks like. Both keyless. */}
        <div
          role="group"
          aria-label="Map style"
          className="flex rounded-full border border-[var(--color-line-strong)] bg-[var(--color-surface)] p-0.5"
        >
          {(["Map", "Satellite", "Terrain"] as BaseLayerName[]).map((name) => (
            <button
              key={name}
              type="button"
              onClick={() => setLayer(name)}
              aria-pressed={layer === name}
              className={`rounded-full px-3 py-1 text-[11px] font-medium transition-colors duration-200 ${
                layer === name
                  ? "bg-[var(--color-brand)] text-white"
                  : "text-[var(--color-ink-soft)] hover:text-[var(--color-brand-strong)]"
              }`}
            >
              {name}
            </button>
          ))}
        </div>

        <button
          type="button"
          onClick={onClose}
          className="rounded-full border border-[var(--color-line-strong)] bg-[var(--color-surface)] px-3 py-1.5 text-xs font-medium transition-colors duration-200 hover:border-[var(--color-brand)]"
        >
          Close
        </button>
      </header>

      <div className="grid min-h-0 flex-1 gap-3 lg:grid-cols-[1fr_16rem]">
        <PlaceMap
          items={pins}
          activeIndex={active}
          focusIndex={focus}
          onHoverItem={setActive}
          onSelectItem={setFocus}
          layer={layer}
          destination={destination}
          showPhotos
          className="h-full min-h-[18rem] rounded-2xl"
        />

        {/* Hover highlights the pin, click flies to it and opens its photo.
            Two behaviours rather than one, because hovering a list should not
            yank the map around while the eye is still scanning. */}
        <ol className="hidden min-h-0 overflow-y-auto rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)] p-2 lg:block">
          {pins.map((pin) => (
            <li key={pin.index}>
              <button
                type="button"
                onMouseEnter={() => setActive(pin.index)}
                onMouseLeave={() => setActive(null)}
                onClick={() => setFocus(pin.index)}
                className={`flex w-full items-center gap-2 rounded-xl px-2 py-1.5 text-left transition-colors duration-150 ${
                  active === pin.index || focus === pin.index
                    ? "bg-[var(--color-brand-soft)]"
                    : "hover:bg-[var(--color-surface-2)]"
                }`}
              >
                <span
                  className="grid size-5 shrink-0 place-items-center rounded-full text-[10px] font-semibold text-white"
                  style={{ background: dayColor(pin.dayNumber) }}
                >
                  {pin.index}
                </span>
                <span className="min-w-0 flex-1 truncate text-[11px] font-medium">{pin.name}</span>
              </button>
            </li>
          ))}
        </ol>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------

/**
 * Assembles the panel stack from the latest reply that had anything to say.
 *
 * Facts are carried forward across turns rather than read from the newest
 * reply alone: asking about hotels and then about the weather must not blank
 * the hotels. The panel shows the trip's current state, and that state is
 * cumulative even though each individual reply is not.
 */
export function TripPanel({
  trip,
  facts,
  pins,
  busy,
  onAsk,
}: {
  trip: TripState;
  facts: { weather?: TripFact; stays?: TripFact; flights?: TripFact };
  pins: MappedItem[];
  busy: boolean;
  /** Sends a message as if the traveller had typed it. */
  onAsk?: (message: string) => void;
}) {
  const destination = (trip.destination as string) ?? "";

  return (
    <div className="space-y-2.5">
      <TripSummary trip={trip} />
      <MapPanel pins={pins} busy={busy} destination={destination} />
      <WeatherPanel fact={facts.weather} busy={busy} trip={trip} onAsk={onAsk} />
      <StaysPanel fact={facts.stays} busy={busy} destination={destination} onAsk={onAsk} />
      <FlightsPanel fact={facts.flights} busy={busy} trip={trip} onAsk={onAsk} />
    </div>
  );
}

/**
 * The same panel on a narrow screen, behind a toggle.
 *
 * A phone cannot show two columns, and stacking the panel above the
 * conversation would put a map between the traveller and the thing they are
 * reading. Collapsed by default, and the count on the button is what tells
 * them there is anything worth opening.
 */
export function TripPanelDrawer(props: Parameters<typeof TripPanel>[0]) {
  const [open, setOpen] = useState(false);
  const filled =
    (props.pins.length > 0 ? 1 : 0) +
    (props.facts.weather ? 1 : 0) +
    (props.facts.stays ? 1 : 0) +
    (props.facts.flights ? 1 : 0);

  return (
    <div className="lg:hidden">
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        className="inline-flex min-h-9 items-center gap-1.5 rounded-full border border-[var(--color-line-strong)] bg-[var(--color-surface)] px-3 text-xs font-medium transition-colors duration-200 hover:border-[var(--color-brand)]"
      >
        <IconPin size="0.95em" />
        {open ? "Hide trip details" : `Trip details${filled > 0 ? ` (${filled})` : ""}`}
      </button>
      {open && (
        <div className="rise-in mt-2">
          <TripPanel {...props} />
        </div>
      )}
    </div>
  );
}
