"""Flight and accommodation search tools.

Thin wrappers over whichever `FlightProvider` is configured. The tools handle
argument validation and the honesty requirement - every response states
plainly whether the data is live or simulated - while the provider owns the
actual search.

The `data_disclaimer` field is not decoration. An agent that presents
simulated fares as bookable is worse than one that offers no fares at all, so
the disclaimer travels with the payload into the model's context and the
tool's `message` instructs the model to repeat it to the user.
"""

from __future__ import annotations

from datetime import datetime
from typing import Final

from app.core.config import Settings, get_settings
from app.core.errors import ToolExecutionError
from app.providers.flights import get_flight_provider
from app.tools.base import ToolResult, resilient_tool

VALID_CABINS: Final[frozenset[str]] = frozenset(
    {"economy", "premium_economy", "business", "first"}
)

FLIGHTS_UNAVAILABLE: Final[str] = (
    "Flight search is unavailable. Continue building the itinerary without transport "
    "costs and tell the user to check fares separately. Do not retry this tool."
)

STAYS_UNAVAILABLE: Final[str] = (
    "Accommodation search is unavailable. Continue building the itinerary and suggest "
    "neighbourhoods to stay in rather than specific properties, telling the user that "
    "live availability could not be checked. Do not retry this tool."
)

SIMULATED_DISCLAIMER: Final[str] = (
    "SIMULATED DATA - these prices and schedules are generated by a mock provider for "
    "demonstration and are not real availability. You MUST tell the user this when "
    "presenting them, and must not imply anything here is bookable."
)


def _validate_date(value: str, field: str, tool_name: str) -> str:
    """Validate an ISO date argument.

    Args:
        value: The date string to check.
        field: Argument name, used in the error message.
        tool_name: Tool name, attached to the raised error.

    Returns:
        The validated date string.

    Raises:
        ToolExecutionError: If the value is not `YYYY-MM-DD`.
    """
    try:
        datetime.strptime(value, "%Y-%m-%d")
    except (ValueError, TypeError) as exc:
        raise ToolExecutionError(
            f"`{field}` must be an ISO date formatted as YYYY-MM-DD "
            f"(for example 2026-09-12). Received: {value!r}.",
            tool_name=tool_name,
        ) from exc
    return value


@resilient_tool(source="flight-provider", unavailable_message=FLIGHTS_UNAVAILABLE)
async def search_flights(
    origin: str,
    destination: str,
    departure_date: str,
    return_date: str | None = None,
    cabin: str = "economy",
    adults: int = 1,
    settings: Settings | None = None,
) -> ToolResult:
    """Search for flights between two cities.

    Use when the user asks about getting to a destination, wants a transport
    budget, or is comparing travel dates. Not needed for planning activities
    once they have already arrived.

    Args:
        origin: Departure city name, e.g. `"Singapore"`.
        destination: Arrival city name, e.g. `"Tokyo"`.
        departure_date: Outbound date as `YYYY-MM-DD`.
        return_date: Optional inbound date as `YYYY-MM-DD` for a round trip.
        cabin: One of `economy`, `premium_economy`, `business`, `first`.
        adults: Number of adult passengers, 1-9.
        settings: Settings override, for tests.

    Returns:
        A `ToolResult` whose data contains the route and a list of priced
        offers, plus a disclaimer describing the data's provenance.
    """
    cfg = settings or get_settings()

    _validate_date(departure_date, "departure_date", "search_flights")
    if return_date:
        _validate_date(return_date, "return_date", "search_flights")
        if return_date < departure_date:
            return ToolResult.invalid(
                source="flight-provider",
                message=(
                    f"`return_date` ({return_date}) is before `departure_date` "
                    f"({departure_date}). Call again with a later return date."
                ),
            )

    normalised_cabin = cabin.strip().lower().replace(" ", "_").replace("-", "_")
    if normalised_cabin not in VALID_CABINS:
        return ToolResult.invalid(
            source="flight-provider",
            message=(
                f"{cabin!r} is not a valid cabin. Choose one of: "
                f"{', '.join(sorted(VALID_CABINS))}."
            ),
        )

    if not 1 <= adults <= 9:
        return ToolResult.invalid(
            source="flight-provider",
            message=f"`adults` must be between 1 and 9. Received: {adults}.",
        )

    provider = get_flight_provider(cfg)
    result = await provider.search_flights(
        origin=origin,
        destination=destination,
        departure_date=departure_date,
        return_date=return_date,
        cabin=normalised_cabin,
        adults=adults,
    )

    if result.get("error") == "unknown_city":
        return ToolResult.invalid(
            source=provider.name,
            message=result.get("message", "One of the cities could not be resolved."),
        )

    is_simulated = not getattr(provider, "is_live", False)
    result["data_disclaimer"] = SIMULATED_DISCLAIMER if is_simulated else "Live provider data."

    offer_count = len(result.get("offers", []))
    return ToolResult.ok(
        source=provider.name,
        data=result,
        message=(
            f"{offer_count} flight options from {origin} to {destination}. "
            + (SIMULATED_DISCLAIMER if is_simulated else "Prices are live and subject to change.")
        ),
    )


@resilient_tool(source="flight-provider", unavailable_message=STAYS_UNAVAILABLE)
async def search_accommodation(
    city: str,
    check_in: str,
    check_out: str,
    guests: int = 2,
    max_price_per_night: float | None = None,
    settings: Settings | None = None,
) -> ToolResult:
    """Search for places to stay in a city.

    Use when the user asks where to stay or wants an accommodation budget.
    Pass `max_price_per_night` whenever a budget is known - including one
    recalled from long-term memory - so results respect it rather than being
    filtered after the fact.

    Args:
        city: City name, e.g. `"Kyoto"`.
        check_in: Arrival date as `YYYY-MM-DD`.
        check_out: Departure date as `YYYY-MM-DD`.
        guests: Number of guests, 1-8.
        max_price_per_night: Optional nightly budget ceiling in USD.
        settings: Settings override, for tests.

    Returns:
        A `ToolResult` whose data contains a list of properties across price
        tiers, plus a disclaimer describing the data's provenance.
    """
    cfg = settings or get_settings()

    _validate_date(check_in, "check_in", "search_accommodation")
    _validate_date(check_out, "check_out", "search_accommodation")

    if check_out <= check_in:
        return ToolResult.invalid(
            source="flight-provider",
            message=(
                f"`check_out` ({check_out}) must be after `check_in` ({check_in}). "
                "A two-day trip normally means two nights."
            ),
        )

    if not 1 <= guests <= 8:
        return ToolResult.invalid(
            source="flight-provider",
            message=f"`guests` must be between 1 and 8. Received: {guests}.",
        )

    provider = get_flight_provider(cfg)
    result = await provider.search_accommodation(
        city=city,
        check_in=check_in,
        check_out=check_out,
        guests=guests,
        max_price_per_night=max_price_per_night,
    )

    if result.get("error") == "unknown_city":
        return ToolResult.invalid(
            source=provider.name,
            message=result.get("message", "The city could not be resolved."),
        )

    is_simulated = not getattr(provider, "is_live", False)
    result["data_disclaimer"] = SIMULATED_DISCLAIMER if is_simulated else "Live provider data."

    properties = result.get("properties", [])
    if not properties and max_price_per_night is not None:
        return ToolResult.ok(
            source=provider.name,
            data=result,
            message=(
                f"No accommodation in {city} under ${max_price_per_night:.0f} per night. "
                "Tell the user their budget is tight for this destination and ask whether "
                "they want to raise it or consider a hostel or a nearby area. "
                + (SIMULATED_DISCLAIMER if is_simulated else "")
            ),
        )

    return ToolResult.ok(
        source=provider.name,
        data=result,
        message=(
            f"{len(properties)} accommodation options in {city} for "
            f"{result.get('nights', '?')} nights. "
            + (SIMULATED_DISCLAIMER if is_simulated else "Live availability.")
        ),
    )
